### ISSUE TITLE
Dead links in platforms.md

### ISSUE THREAD

**Issue by atouchet** [serialport/serialport-rs#85]
https://github.com/serialport/serialport-rs/blob/d60df349623f9ae526513a12bee5b756d7c769bd/doc/platforms.md?plain=1#L27-L28

**Comment by sirhcel** [comment]
Thank you very much for pointing this out! I have no experience with NetBSD, but since you are here: are the following links the man pages you were looking for:

- https://man.netbsd.org/NetBSD-8.0/i386/tty.4
- https://man.netbsd.org/NetBSD-8.0/i386/com.4

Do you see anything against pointing to the man pages for the current NetBSD release and without a specific archtiecture? Like:

- https://man.netbsd.org/tty.4
- https://man.netbsd.org/com.4

**Comment by eldruin** [comment]
@atouchet would you mind opening a PR fixing the links?

**Comment by atouchet** [comment]
Sure, I opened a PR here: #86
